import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface AccountslistInput {}

export type AccountslistOutput = unknown;

/**
 * List all accounts in your Cloudflare account
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `accounts_list`
 * @param input Tool input
 * @returns Tool output
 */
export async function accountsList(input: AccountslistInput): Promise<AccountslistOutput> {
  return await callMcpTool<AccountslistOutput>({
    serverName: "cloudflare-observability",
    toolName: "accounts_list",
    input,
  });
}
