import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface MigratepagestoworkersguideInput {}

export type MigratepagestoworkersguideOutput = unknown;

/**
 * ALWAYS read this guide before migrating Pages projects to Workers.
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `migrate_pages_to_workers_guide`
 * @param input Tool input
 * @returns Tool output
 */
export async function migratePagesToWorkersGuide(
  input: MigratepagestoworkersguideInput,
): Promise<MigratepagestoworkersguideOutput> {
  return await callMcpTool<MigratepagestoworkersguideOutput>({
    serverName: "cloudflare-observability",
    toolName: "migrate_pages_to_workers_guide",
    input,
  });
}
