import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ObservabilityvaluesInput {
  valuesQuery: Record<string, unknown>;
}

export type ObservabilityvaluesOutput = unknown;

/**
 * Find values in the Workers Observability Data.

## Troubleshooting
- For no results, verify the field exists using observability_keys first
- If expected values are missing, try broadening your time range
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `observability_values`
 * @param input Tool input
 * @returns Tool output
 */
export async function observabilityValues(
  input: ObservabilityvaluesInput,
): Promise<ObservabilityvaluesOutput> {
  return await callMcpTool<ObservabilityvaluesOutput>({
    serverName: "cloudflare-observability",
    toolName: "observability_values",
    input,
  });
}
