import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ObservabilitykeysInput {
  keysQuery: Record<string, unknown>;
}

export type ObservabilitykeysOutput = unknown;

/**
 * Find keys in the Workers Observability Data

## Best Practices
- Set a high limit (1000+) to ensure you see all available keys
- Add the $metadata.service filter to narrow results to a specific Worker

## Troubleshooting
- If expected fields are missing, verify the Worker is actively logging
- For empty results, try broadening your time range

 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `observability_keys`
 * @param input Tool input
 * @returns Tool output
 */
export async function observabilityKeys(
  input: ObservabilitykeysInput,
): Promise<ObservabilitykeysOutput> {
  return await callMcpTool<ObservabilitykeysOutput>({
    serverName: "cloudflare-observability",
    toolName: "observability_keys",
    input,
  });
}
