import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface QueryworkerobservabilityInput {
  query: Record<string, unknown>;
}

export type QueryworkerobservabilityOutput = unknown;

/**
 * Query the Workers Observability API to analyze logs and metrics from your Cloudflare Workers.

	* A query typical query looks like this:
				{"view":"events","queryId":"workers-logs-events","limit":5,"dry":true,"parameters":{"datasets":["cloudflare-workers"],"filters":[{"id":"520","key":"message","operation":"eq","type":"string","value":"Clickhouse Statistics"},{"id":"2088","key":"statistics.elapsed","operation":"gt","type":"number","value":"0.269481519"}],"calculations":[],"groupBys":[],"havings":[]},"timeframe":{"to":"2025-04-30T20:53:15Z","from":" ""2025-04-30T19:53:15Z"}}
## Core Capabilities
This tool provides three primary views of your Worker data:
1. **List Events** - Browse individual request logs and errors
2. **Calculate Metrics** - Compute statistics across requests (avg, p99, etc.)
3. **Find Specific Invocations** - Locate individual requests matching criteria

## Filtering Best Practices
- Before applying filters, use the observability_keys and observability_values tools to confirm available filter fields and the correct filter value to add unless you have the data in a response from a previous query.
- Common filter fields:  $metadata.service, $metadata.trigger, $metadata.message, $metadata.level, $metadata.requestId,

## Calculation Best Practices
- Before applying calculations, use the observability_keys tools to confirm key that should be used for the calculation

## Troubleshooting
- If no results are returned, suggest broadening the time range or relaxing filters
- For errors about invalid fields, recommend using observability_keys to see available options

 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `query_worker_observability`
 * @param input Tool input
 * @returns Tool output
 */
export async function queryWorkerObservability(
  input: QueryworkerobservabilityInput,
): Promise<QueryworkerobservabilityOutput> {
  return await callMcpTool<QueryworkerobservabilityOutput>({
    serverName: "cloudflare-observability",
    toolName: "query_worker_observability",
    input,
  });
}
