import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface SearchcloudflaredocumentationInput {
  query: string;
}

export type SearchcloudflaredocumentationOutput = unknown;

/**
 * Search the Cloudflare documentation.

		This tool should be used to answer any question about Cloudflare products or features, including:
		- Workers, Pages, R2, Images, Stream, D1, Durable Objects, KV, Workflows, Hyperdrive, Queues
		- AI Search, Workers AI, Vectorize, AI Gateway, Browser Rendering
		- Zero Trust, Access, Tunnel, Gateway, Browser Isolation, WARP, DDOS, Magic Transit, Magic WAN
		- CDN, Cache, DNS, Zaraz, Argo, Rulesets, Terraform, Account and Billing

		Results are returned as semantically similar chunks to the query.
		
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `search_cloudflare_documentation`
 * @param input Tool input
 * @returns Tool output
 */
export async function searchCloudflareDocumentation(
  input: SearchcloudflaredocumentationInput,
): Promise<SearchcloudflaredocumentationOutput> {
  return await callMcpTool<SearchcloudflaredocumentationOutput>({
    serverName: "cloudflare-observability",
    toolName: "search_cloudflare_documentation",
    input,
  });
}
