import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface SetactiveaccountInput {
  activeAccountIdParam: string;
}

export type SetactiveaccountOutput = unknown;

/**
 * Set active account to be used for tool calls that require accountId
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `set_active_account`
 * @param input Tool input
 * @returns Tool output
 */
export async function setActiveAccount(
  input: SetactiveaccountInput,
): Promise<SetactiveaccountOutput> {
  return await callMcpTool<SetactiveaccountOutput>({
    serverName: "cloudflare-observability",
    toolName: "set_active_account",
    input,
  });
}
