import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface WorkersgetworkercodeInput {
  scriptName: string;
}

export type WorkersgetworkercodeOutput = unknown;

/**
 * Get the source code of a Cloudflare Worker. Note: This may be a bundled version of the worker.
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `workers_get_worker_code`
 * @param input Tool input
 * @returns Tool output
 */
export async function workersGetWorkerCode(
  input: WorkersgetworkercodeInput,
): Promise<WorkersgetworkercodeOutput> {
  return await callMcpTool<WorkersgetworkercodeOutput>({
    serverName: "cloudflare-observability",
    toolName: "workers_get_worker_code",
    input,
  });
}
