import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface WorkerslistInput {}

export type WorkerslistOutput = unknown;

/**
 * List all Workers in your Cloudflare account.

If you only need details of a single Worker, use workers_get_worker.
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `workers_list`
 * @param input Tool input
 * @returns Tool output
 */
export async function workersList(input: WorkerslistInput): Promise<WorkerslistOutput> {
  return await callMcpTool<WorkerslistOutput>({
    serverName: "cloudflare-observability",
    toolName: "workers_list",
    input,
  });
}
