import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface WorkersgetworkerInput {
  scriptName: string;
}

export type WorkersgetworkerOutput = unknown;

/**
 * Get the details of the Cloudflare Worker.
 *
 * MCP server: `cloudflare-observability`
 * MCP tool: `workers_get_worker`
 * @param input Tool input
 * @returns Tool output
 */
export async function workersGetWorker(
  input: WorkersgetworkerInput,
): Promise<WorkersgetworkerOutput> {
  return await callMcpTool<WorkersgetworkerOutput>({
    serverName: "cloudflare-observability",
    toolName: "workers_get_worker",
    input,
  });
}
