import fs from "node:fs/promises";
import path from "node:path";
import { toCamelCase, toPascalCase } from "./names.js";
import { jsonSchemaToTsInterface } from "./jsonSchemaToTs.js";
import type { IntrospectedServer } from "../../introspect/types.js";

export async function generateServerTs(args: {
  outDir: string;
  serverSlug: string;
  registryId: string;
  snapshot: IntrospectedServer;
}) {
  const serverDir = path.join(args.outDir, "servers", args.serverSlug);
  const toolsDir = path.join(serverDir, "tools");
  await fs.mkdir(toolsDir, { recursive: true });

  const usedNames = new Map<string, number>();
  const exports: string[] = [];

  for (const tool of args.snapshot.tools) {
    const baseFn = toCamelCase(tool.name);
    const n = usedNames.get(baseFn) ?? 0;
    usedNames.set(baseFn, n + 1);
    const fnName = n === 0 ? baseFn : `${baseFn}__${n + 1}`;

    const inputTypeName = `${toPascalCase(fnName)}Input`;
    const outputTypeName = `${toPascalCase(fnName)}Output`;
    const fileName = `${fnName}.ts`;
    const filePath = path.join(toolsDir, fileName);

    const ts = [
      `import { callMcpTool } from "mcp-toolbox/runtime";`,
      ``,
      `// server: ${args.registryId}`,
      `// tool: ${tool.name}`,
      tool.description ? `// ${tool.description}` : `//`,
      ``,
      jsonSchemaToTsInterface(inputTypeName, tool.inputSchema),
      `export type ${outputTypeName} = unknown;`,
      ``,
      `export async function ${fnName}(input: ${inputTypeName}): Promise<${outputTypeName}> {`,
      `  return await callMcpTool<${outputTypeName}>({`,
      `    registryId: ${JSON.stringify(args.registryId)},`,
      `    toolName: ${JSON.stringify(tool.name)},`,
      `    input,`,
      `  });`,
      `}`,
      ``,
    ].join("\n");

    await fs.writeFile(filePath, ts, "utf-8");
    exports.push(`export * from "./tools/${fnName}.js";`);
  }

  const indexTs = [
    `// Generated by mcp-toolbox. Do not edit by hand.`,
    `// registryId: ${args.registryId}`,
    ``,
    ...exports,
    ``,
  ].join("\n");

  await fs.writeFile(path.join(serverDir, "index.ts"), indexTs, "utf-8");
}

