import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ApplymigrationInput {
  name: string;
  query: string;
}

export type ApplymigrationOutput = unknown;

/**
 * Applies a migration to the database. Use this when executing DDL operations. Do not hardcode references to generated IDs in data migrations.
 *
 * MCP server: `supabase`
 * MCP tool: `apply_migration`
 * @param input Tool input
 * @returns Tool output
 */
export async function applyMigration(input: ApplymigrationInput): Promise<ApplymigrationOutput> {
  return await callMcpTool<ApplymigrationOutput>({
    serverName: "supabase",
    toolName: "apply_migration",
    input,
  });
}
