import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface CreatebranchInput {
  name: string;
  confirm_cost_id: string;
}

export type CreatebranchOutput = unknown;

/**
 * Creates a development branch on a Supabase project. This will apply all migrations from the main project to a fresh branch database. Note that production data will not carry over. The branch will get its own project_id via the resulting project_ref. Use this ID to execute queries and migrations on the branch.
 *
 * MCP server: `supabase`
 * MCP tool: `create_branch`
 * @param input Tool input
 * @returns Tool output
 */
export async function createBranch(input: CreatebranchInput): Promise<CreatebranchOutput> {
  return await callMcpTool<CreatebranchOutput>({
    serverName: "supabase",
    toolName: "create_branch",
    input,
  });
}
