import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface DeletebranchInput {
  branch_id: string;
}

export type DeletebranchOutput = unknown;

/**
 * Deletes a development branch.
 *
 * MCP server: `supabase`
 * MCP tool: `delete_branch`
 * @param input Tool input
 * @returns Tool output
 */
export async function deleteBranch(input: DeletebranchInput): Promise<DeletebranchOutput> {
  return await callMcpTool<DeletebranchOutput>({
    serverName: "supabase",
    toolName: "delete_branch",
    input,
  });
}
