import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface DeployedgefunctionInput {
  name: string;
  entrypoint_path: string;
  import_map_path?: string;
  verify_jwt: boolean;
  files: Record<string, unknown>[];
}

export type DeployedgefunctionOutput = unknown;

/**
 * Deploys an Edge Function to a Supabase project. If the function already exists, this will create a new version. Example:

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

Deno.serve(async (req: Request) => {
  const data = {
    message: "Hello there!"
  };
  
  return new Response(JSON.stringify(data), {
    headers: {
      'Content-Type': 'application/json',
      'Connection': 'keep-alive'
    }
  });
});
 *
 * MCP server: `supabase`
 * MCP tool: `deploy_edge_function`
 * @param input Tool input
 * @returns Tool output
 */
export async function deployEdgeFunction(
  input: DeployedgefunctionInput,
): Promise<DeployedgefunctionOutput> {
  return await callMcpTool<DeployedgefunctionOutput>({
    serverName: "supabase",
    toolName: "deploy_edge_function",
    input,
  });
}
