import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GeneratetypescripttypesInput {}

export type GeneratetypescripttypesOutput = unknown;

/**
 * Generates TypeScript types for a project.
 *
 * MCP server: `supabase`
 * MCP tool: `generate_typescript_types`
 * @param input Tool input
 * @returns Tool output
 */
export async function generateTypescriptTypes(
  input: GeneratetypescripttypesInput,
): Promise<GeneratetypescripttypesOutput> {
  return await callMcpTool<GeneratetypescripttypesOutput>({
    serverName: "supabase",
    toolName: "generate_typescript_types",
    input,
  });
}
