import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GetadvisorsInput {
  type: string;
}

export type GetadvisorsOutput = unknown;

/**
 * Gets a list of advisory notices for the Supabase project. Use this to check for security vulnerabilities or performance improvements. Include the remediation URL as a clickable link so that the user can reference the issue themselves. It's recommended to run this tool regularly, especially after making DDL changes to the database since it will catch things like missing RLS policies.
 *
 * MCP server: `supabase`
 * MCP tool: `get_advisors`
 * @param input Tool input
 * @returns Tool output
 */
export async function getAdvisors(input: GetadvisorsInput): Promise<GetadvisorsOutput> {
  return await callMcpTool<GetadvisorsOutput>({
    serverName: "supabase",
    toolName: "get_advisors",
    input,
  });
}
