import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GetedgefunctionInput {
  function_slug: string;
}

export type GetedgefunctionOutput = unknown;

/**
 * Retrieves file contents for an Edge Function in a Supabase project.
 *
 * MCP server: `supabase`
 * MCP tool: `get_edge_function`
 * @param input Tool input
 * @returns Tool output
 */
export async function getEdgeFunction(input: GetedgefunctionInput): Promise<GetedgefunctionOutput> {
  return await callMcpTool<GetedgefunctionOutput>({
    serverName: "supabase",
    toolName: "get_edge_function",
    input,
  });
}
