import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GetlogsInput {
  service: string;
}

export type GetlogsOutput = unknown;

/**
 * Gets logs for a Supabase project by service type. Use this to help debug problems with your app. This will return logs within the last 24 hours.
 *
 * MCP server: `supabase`
 * MCP tool: `get_logs`
 * @param input Tool input
 * @returns Tool output
 */
export async function getLogs(input: GetlogsInput): Promise<GetlogsOutput> {
  return await callMcpTool<GetlogsOutput>({
    serverName: "supabase",
    toolName: "get_logs",
    input,
  });
}
