import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GetpublishablekeysInput {}

export type GetpublishablekeysOutput = unknown;

/**
 * Gets all publishable API keys for a project, including legacy anon keys (JWT-based) and modern publishable keys (format: sb_publishable_...). Publishable keys are recommended for new applications due to better security and independent rotation. Legacy anon keys are included for compatibility, as many LLMs are pretrained on them. Disabled keys are indicated by the "disabled" field; only use keys where disabled is false or undefined.
 *
 * MCP server: `supabase`
 * MCP tool: `get_publishable_keys`
 * @param input Tool input
 * @returns Tool output
 */
export async function getPublishableKeys(
  input: GetpublishablekeysInput,
): Promise<GetpublishablekeysOutput> {
  return await callMcpTool<GetpublishablekeysOutput>({
    serverName: "supabase",
    toolName: "get_publishable_keys",
    input,
  });
}
