import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface GetprojecturlInput {}

export type GetprojecturlOutput = unknown;

/**
 * Gets the API URL for a project.
 *
 * MCP server: `supabase`
 * MCP tool: `get_project_url`
 * @param input Tool input
 * @returns Tool output
 */
export async function getProjectUrl(input: GetprojecturlInput): Promise<GetprojecturlOutput> {
  return await callMcpTool<GetprojecturlOutput>({
    serverName: "supabase",
    toolName: "get_project_url",
    input,
  });
}
