import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ListbranchesInput {}

export type ListbranchesOutput = unknown;

/**
 * Lists all development branches of a Supabase project. This will return branch details including status which you can use to check when operations like merge/rebase/reset complete.
 *
 * MCP server: `supabase`
 * MCP tool: `list_branches`
 * @param input Tool input
 * @returns Tool output
 */
export async function listBranches(input: ListbranchesInput): Promise<ListbranchesOutput> {
  return await callMcpTool<ListbranchesOutput>({
    serverName: "supabase",
    toolName: "list_branches",
    input,
  });
}
