import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ListedgefunctionsInput {}

export type ListedgefunctionsOutput = unknown;

/**
 * Lists all Edge Functions in a Supabase project.
 *
 * MCP server: `supabase`
 * MCP tool: `list_edge_functions`
 * @param input Tool input
 * @returns Tool output
 */
export async function listEdgeFunctions(
  input: ListedgefunctionsInput,
): Promise<ListedgefunctionsOutput> {
  return await callMcpTool<ListedgefunctionsOutput>({
    serverName: "supabase",
    toolName: "list_edge_functions",
    input,
  });
}
