import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ListmigrationsInput {}

export type ListmigrationsOutput = unknown;

/**
 * Lists all migrations in the database.
 *
 * MCP server: `supabase`
 * MCP tool: `list_migrations`
 * @param input Tool input
 * @returns Tool output
 */
export async function listMigrations(input: ListmigrationsInput): Promise<ListmigrationsOutput> {
  return await callMcpTool<ListmigrationsOutput>({
    serverName: "supabase",
    toolName: "list_migrations",
    input,
  });
}
