import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ListtablesInput {
  schemas: string[];
}

export type ListtablesOutput = unknown;

/**
 * Lists all tables in one or more schemas.
 *
 * MCP server: `supabase`
 * MCP tool: `list_tables`
 * @param input Tool input
 * @returns Tool output
 */
export async function listTables(input: ListtablesInput): Promise<ListtablesOutput> {
  return await callMcpTool<ListtablesOutput>({
    serverName: "supabase",
    toolName: "list_tables",
    input,
  });
}
