import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ListextensionsInput {}

export type ListextensionsOutput = unknown;

/**
 * Lists all extensions in the database.
 *
 * MCP server: `supabase`
 * MCP tool: `list_extensions`
 * @param input Tool input
 * @returns Tool output
 */
export async function listExtensions(input: ListextensionsInput): Promise<ListextensionsOutput> {
  return await callMcpTool<ListextensionsOutput>({
    serverName: "supabase",
    toolName: "list_extensions",
    input,
  });
}
