import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface MergebranchInput {
  branch_id: string;
}

export type MergebranchOutput = unknown;

/**
 * Merges migrations and edge functions from a development branch to production.
 *
 * MCP server: `supabase`
 * MCP tool: `merge_branch`
 * @param input Tool input
 * @returns Tool output
 */
export async function mergeBranch(input: MergebranchInput): Promise<MergebranchOutput> {
  return await callMcpTool<MergebranchOutput>({
    serverName: "supabase",
    toolName: "merge_branch",
    input,
  });
}
