import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface RebasebranchInput {
  branch_id: string;
}

export type RebasebranchOutput = unknown;

/**
 * Rebases a development branch on production. This will effectively run any newer migrations from production onto this branch to help handle migration drift.
 *
 * MCP server: `supabase`
 * MCP tool: `rebase_branch`
 * @param input Tool input
 * @returns Tool output
 */
export async function rebaseBranch(input: RebasebranchInput): Promise<RebasebranchOutput> {
  return await callMcpTool<RebasebranchOutput>({
    serverName: "supabase",
    toolName: "rebase_branch",
    input,
  });
}
