import { callMcpTool } from "mcp-toolbox-runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface ResetbranchInput {
  branch_id: string;
  migration_version?: string;
}

export type ResetbranchOutput = unknown;

/**
 * Resets migrations of a development branch. Any untracked data or schema changes will be lost.
 *
 * MCP server: `supabase`
 * MCP tool: `reset_branch`
 * @param input Tool input
 * @returns Tool output
 */
export async function resetBranch(input: ResetbranchInput): Promise<ResetbranchOutput> {
  return await callMcpTool<ResetbranchOutput>({
    serverName: "supabase",
    toolName: "reset_branch",
    input,
  });
}
