import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FsanalyzediskusageInput {
  path: string;
  depth?: string;
  groupByType?: string;
}

export type FsanalyzediskusageOutput = unknown;

/**
 * Analyze disk usage
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_analyze_disk_usage`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsAnalyzeDiskUsage(
  input: FsanalyzediskusageInput,
): Promise<FsanalyzediskusageOutput> {
  return await callMcpTool<FsanalyzediskusageOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_analyze_disk_usage",
    input,
  });
}
