import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FsbatchoperationsInput {
  operations: string;
  atomic?: string;
}

export type FsbatchoperationsOutput = unknown;

/**
 * Execute multiple filesystem operations atomically
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_batch_operations`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsBatchOperations(
  input: FsbatchoperationsInput,
): Promise<FsbatchoperationsOutput> {
  return await callMcpTool<FsbatchoperationsOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_batch_operations",
    input,
  });
}
