import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FsbuildindexInput {
  path: string;
  includeContent?: string;
}

export type FsbuildindexOutput = unknown;

/**
 * Build file index for fast searching
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_build_index`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsBuildIndex(input: FsbuildindexInput): Promise<FsbuildindexOutput> {
  return await callMcpTool<FsbuildindexOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_build_index",
    input,
  });
}
