import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FscomputechecksumInput {
  path: string;
  algorithm?: string;
}

export type FscomputechecksumOutput = unknown;

/**
 * Compute file checksums
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_compute_checksum`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsComputeChecksum(
  input: FscomputechecksumInput,
): Promise<FscomputechecksumOutput> {
  return await callMcpTool<FscomputechecksumOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_compute_checksum",
    input,
  });
}
