import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FscopydirectoryInput {
  source: string;
  destination: string;
  preserveMetadata?: string;
  exclusions?: string;
}

export type FscopydirectoryOutput = unknown;

/**
 * Copy directories recursively
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_copy_directory`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsCopyDirectory(input: FscopydirectoryInput): Promise<FscopydirectoryOutput> {
  return await callMcpTool<FscopydirectoryOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_copy_directory",
    input,
  });
}
