import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FscreatesymlinkInput {
  linkPath: string;
  targetPath: string;
}

export type FscreatesymlinkOutput = unknown;

/**
 * Create symbolic links
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_create_symlink`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsCreateSymlink(input: FscreatesymlinkInput): Promise<FscreatesymlinkOutput> {
  return await callMcpTool<FscreatesymlinkOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_create_symlink",
    input,
  });
}
