import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FsgetwatcheventsInput {
  sessionId: string;
  clear?: string;
}

export type FsgetwatcheventsOutput = unknown;

/**
 * Get accumulated watch events
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_get_watch_events`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsGetWatchEvents(
  input: FsgetwatcheventsInput,
): Promise<FsgetwatcheventsOutput> {
  return await callMcpTool<FsgetwatcheventsOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_get_watch_events",
    input,
  });
}
