import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FssearchfilesInput {
  query: string;
  searchType?: string;
  fileTypes?: string;
  minSize?: string;
  maxSize?: string;
  modifiedAfter?: string;
  useIndex?: string;
}

export type FssearchfilesOutput = unknown;

/**
 * Search for files by name, content, or metadata
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_search_files`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsSearchFiles(input: FssearchfilesInput): Promise<FssearchfilesOutput> {
  return await callMcpTool<FssearchfilesOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_search_files",
    input,
  });
}
