import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FsstopwatchInput {
  sessionId: string;
}

export type FsstopwatchOutput = unknown;

/**
 * Stop watching a directory
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_stop_watch`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsStopWatch(input: FsstopwatchInput): Promise<FsstopwatchOutput> {
  return await callMcpTool<FsstopwatchOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_stop_watch",
    input,
  });
}
