import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FssyncdirectoryInput {
  source: string;
  destination: string;
  exclusions?: string;
}

export type FssyncdirectoryOutput = unknown;

/**
 * Sync directories (copy only newer or missing files)
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_sync_directory`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsSyncDirectory(input: FssyncdirectoryInput): Promise<FssyncdirectoryOutput> {
  return await callMcpTool<FssyncdirectoryOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_sync_directory",
    input,
  });
}
