import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FsverifychecksumInput {
  path: string;
  checksum: string;
  algorithm?: string;
}

export type FsverifychecksumOutput = unknown;

/**
 * Verify file checksums
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_verify_checksum`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsVerifyChecksum(
  input: FsverifychecksumInput,
): Promise<FsverifychecksumOutput> {
  return await callMcpTool<FsverifychecksumOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_verify_checksum",
    input,
  });
}
