import { callMcpTool } from "mcp-toolbox/runtime";

// Generated by mcp-toolbox. Do not edit by hand.

export interface FswatchdirectoryInput {
  path: string;
  recursive?: string;
  filters?: string;
}

export type FswatchdirectoryOutput = unknown;

/**
 * Watch directory for filesystem changes
 *
 * MCP server: `io.github.Digital-Defiance/mcp-filesystem`
 * MCP tool: `fs_watch_directory`
 * @param input Tool input
 * @returns Tool output
 */
export async function fsWatchDirectory(
  input: FswatchdirectoryInput,
): Promise<FswatchdirectoryOutput> {
  return await callMcpTool<FswatchdirectoryOutput>({
    registryId: "io.github.Digital-Defiance/mcp-filesystem",
    toolName: "fs_watch_directory",
    input,
  });
}
